import Head from "next/head";


function Settings() {
	return (
		<>
			<Head key="111">
				<title>Your Settings</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="grid h-screen content-center text-center text-white">
				<h1 className="text-4xl">Comming Soon🔥</h1>
				<p>Page Under Construction🚧</p>
			</div>
		</>
	);
}

export default Settings;
